spring.config.import=file:env.properties
#SERVER CONFIG
server.port=${PORT}
#DB CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/${PG_DB_NAME}
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
#HIBERNATE CONFIG
spring.jpa.hibernate.ddl-auto=HIBERNATE_AUTO
#JWT
jwt.secret=${JWT_SECRET}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
#Specifica il dialetto per PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#Cloudinary
cloudinary.name=${CLOUDINARY_NAME}
cloudinary.apikey=${CLOUDINARY_API_KEY}
cloudinary.secret=${CLOUDINARY_SECRET}